server:
  port: 1003

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML5
    cache: false
    suffix: .html
    encoding: UTF-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml

mybatis:
  configuration:
    #自动将数据库带下划线的表字段值映射到Java类的驼峰字段上
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
